### ISSUE TITLE
Startup menu error dialog's OK button does not function

### ISSUE THREAD

**Issue by ZarothYe** [H-uru/Plasma#1031]
The startup dialog (player selection, etc.) can show an error message dialog in several different scenarios. For example:
- Trying to Create Explorer with a blank name
- Trying to Create Explorer with a blank gender
- Trying to Create Explorer with 2 or more spaces in the middle of their name
- Trying to log in with a player that is already logged in from another client instance (I might be a little forgetful, ok?)

This error dialog is the dialog with key "GUIDialog04d". When this dialog pops up, clicking the "OK" button does not close the error dialog or return you to the intended previous dialog to continue on with your life. The only way to proceed is to close the client. This only a problem with H'uru; I have verified that the same dialog in MOULa works correctly. There does not appear to be any discernable error messages in any of the log files when this happens.

![image](https://user-images.githubusercontent.com/94947971/143661119-295f9f3c-5a9d-4d26-a9ac-459efdf94856.png)

**Comment by Deledrius** [comment]
Thanks for the bug report.  I can confirm I see this behavior as well.
