### ISSUE TITLE
Missing `<memory>` includes

### ISSUE THREAD

**Issue by dgelessus** [H-uru/Plasma#1081]
pfGUITextBoxMod.cpp and plInterMeshSmooth.cpp use `std::unique_ptr` and `std::make_unique`, but don't include `<memory>`, giving me compile errors. I'm guessing this went unnoticed because of unity builds. (Though I get errors both with and without `-DPLASMA_UNITY_BUILD=OFF` - maybe my setup causes the unity build to group files differently?)

I would have made a PR for this, but I don't know the Plasma/H'uru source structure and coding conventions very well, so I'm not sure if `<memory>` should be included directly or through some shared header.

**Comment by dpogue** [comment]
Where possible, we prefer includes to be in the cpp files, so adding it to both of those files should be fine
