### ISSUE TITLE
Odd behavior of avatar selection screen if account has no avatars

### ISSUE THREAD

**Issue by dgelessus** [H-uru/Plasma#1169]
To reproduce (tested using H-uru/Plasma@1484c5988ac369e4a15c6a41d9126977b63c3390 and H-uru/moul-assets@3de1a1fdd3d6443de8c82a61fa5ff66b328e7ae7):

1. Have an account with no avatars - either completely fresh, or by deleting all avvies in an existing account
2. Log in
3. When the game asks you to create an explorer, click "Back"

Now you are on the avatar selection screen with no available avatars (all six slots are labeled "CREATE EXPLORER"). A couple of things behave weirdly here:

* The visitor slot is disabled completely - it doesn't get highlighted when you hover over it, and clicking it does nothing.
  * This also happens when you do have avatars. I'm guessing this has to do with H-uru/moul-assets#114 and will fix itself once that is merged.
* Clicking on the first slot (under EXPLORERS) does nothing, even though the cursor indicates a click spot. This is unexpected - if I have no avatars, I logically want to create my first avatar in the first slot.
  * All slots further below are clickable and let you create a new avatar as expected.
* Clicking on "Explore URU" brings up the "Preparing to Link..." window and then hangs there forever. The Python log shows this traceback:

```
cPyDialogStartUp - Traceback (most recent call last):
  File ".\python\xDialogStartUp.py", line 277, in OnGUINotify
    playerID = gPlayerList[gSelectedSlot-gMinusExplorer][1]
TypeError: 'NoneType' object is not subscriptable
```

**Comment by ZarothYe** [comment]
I think I have a fix for this, but I need to spin up a docker server so I don't blow away all my test toons on TL unnecessarily in order to try it the fix. ;) Thanks for the report!
