### ISSUE TITLE
Garbled Text when System Scaling >= 300%

### ISSUE THREAD

**Issue by patmauro** [H-uru/Plasma#1214]
When system scaling is set to a value >= 300% (ie a high resolution display such as a 4K display is connected), lowercase characters **t-z** stop displaying correctly in a few key contexts in-game, resulting in bizarre garbled text. This is seen most noticeably when mousing over other player characters, but can also be seen in loading screens and the plasma console itself. This has been reproduced on multiple machines and on both OU and H'uru clients.

![image](https://user-images.githubusercontent.com/6642931/177893860-21ed5eec-8954-4229-ae27-7a2de06f34d6.png)
![image](https://user-images.githubusercontent.com/6642931/177893693-11a22218-ba1f-496a-94fd-3b271324d013.png)
![image](https://user-images.githubusercontent.com/6642931/177893709-7815f1a2-fa65-49c3-bde0-c7af91d3024d.png)
![image](https://user-images.githubusercontent.com/6642931/177893734-47b75161-57f0-4d73-897c-125b00bb0e1d.png)

Note that while this is similar to issue https://github.com/H-uru/Plasma/issues/636, it does not appear to be related. Note also that in that case, the "pixellation" issues can be fixed by setting UruExplorer.exe specifically to override system scaling settings and setting to "Scaling Performed By: Application." In this case, the text garbling occurs regardless of what scaling method is set here and what resolution the game is set to run in - as long as system scaling is set to a value >= 300%, this issue will kick in.

**Comment by Hoikas** [comment]
Confirmed. This seems to be another case of #636. In my testing, the issue did not appear until I forced an override for "Scaling Performed By: Application." This indicates that when #636 is fixed completely and correctly, this problem will also be fixed. Of note: Windows doesn't offer above 225% scaling on my system and gives an ominous warning about custom scaling.

**Comment by dgelessus** [comment]
> Of note: Windows doesn't offer above 225% scaling on my system and gives an ominous warning about custom scaling.

I think the maximum scale shown in the dropdown menu depends on the resolution of your screen. For example, at 1024x768 I get only 125%, at 1920x1080 it allows up to 175%, and at 3000x2000 (MS Surface Go built-in screen) up to 200%. Maybe with a 4K screen it displays the 300% option.
