### ISSUE TITLE
Errors during submodule fetch

### ISSUE THREAD

**Issue by Hoikas** [H-uru/Plasma#1216]
```
PS D:\Plasma\CyanWorlds.comEngine> git fetch origin
remote: Enumerating objects: 191, done.
remote: Counting objects: 100% (137/137), done.
remote: Compressing objects: 100% (40/40), done.
remote: Total 95 (delta 61), reused 83 (delta 53), pack-reused 0
Unpacking objects: 100% (95/95), 12.26 KiB | 55.00 KiB/s, done.
From https://github.com/H-uru/Plasma
   306247108..735653c91  master     -> origin/master
Fetching submodule Sources/Tests/gtest
fatal: couldn't find remote ref refs/heads/master
From https://github.com/google/googletest
 * branch              58d77fa8070e8cec2dc1ed015d66b454c8d78850 -> FETCH_HEAD
Errors during submodule fetch:
        gtest
```

**Comment by dpogue** [comment]
What happened is that the google/googletest repo renamed their primary branch from `master` to `main`, but if you had previously set up the submodule it will keep trying to pull from `master` (which no longer exists). This should only affect existing clones with existing submodules (as evidenced by CI passing with fresh checkouts).

I ended up manually fixing this in my clone by editing `.git/modules/gtest/config` and replacing `master` with `main`.
I'm not sure if there's a better way to automatically fix this or not 😞

**Comment by dgelessus** [comment]
FWIW, a default clone of the repo won't be affected by this. The .gitmodules section for `gtest` specifies `branch = release-1.11.0`, so nothing will reference the gtest `master`/`main` branch unless you check it out manually.
