### ISSUE TITLE
Yeesha Page 8 onGUINotify issue

### ISSUE THREAD

**Issue by Hazado** [H-uru/Plasma#1274]
Yeesha Page 8 (Holographic page in rainy cleft) will stop receiving onGUINotify messages after clicking on another yeesha page in rainy cleft.

Once you have clicked on another Yeesha Page in the rainy cleft, xYeeshaPages onGUINotify will receive all the messages.
If you click on page 8 first, it will be clftYeeshaPage08 that gets the onGUINotify

All Yeesha Pages use the the same GUI
Yeesha Page 8 has a custom script to enable the holographic

clftYeeshaPage08.py - Yeesha Page 8
xYeeshaPages.py - All Yeesha Pages

**Comment by Hoikas** [comment]
Closed by #1275.
