### ISSUE TITLE
Dependency errors when trying to clone & build from VS2022

### ISSUE THREAD

**Issue by DamnBriggsy** [H-uru/Plasma#1290]
When attempting to clone the H-uru/Plasma repo from within VS2022, a dialog box with the following error is displayed:
"One or more projects in the solution were not loaded correctly. Please see the output window for details."

The output window shows:
```M:\Plasma\vcpkg\ports\sdl1\SDL\SDL.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'M:\Plasma\vcpkg\ports\sdl1\SDL\SDL.vcxproj'.  M:\Plasma\vcpkg\ports\sdl1\SDL\SDL.vcxproj

M:\Plasma\vcpkg\ports\sdl1\SDL\SDL.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'M:\Plasma\vcpkg\ports\sdl1\SDL\SDL.vcxproj'.  M:\Plasma\vcpkg\ports\sdl1\SDL\SDL.vcxproj

M:\Plasma\vcpkg\ports\sdl1\SDLmain\SDLmain.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'M:\Plasma\vcpkg\ports\sdl1\SDLmain\SDLmain.vcxproj'.  M:\Plasma\vcpkg\ports\sdl1\SDLmain\SDLmain.vcxproj

M:\Plasma\vcpkg\ports\sdl1\SDLmain\SDLmain.vcxproj : error  : The project file could not be loaded. Could not find a part of the path 'M:\Plasma\vcpkg\ports\sdl1\SDLmain\SDLmain.vcxproj'.  M:\Plasma\vcpkg\ports\sdl1\SDLmain\SDLmain.vcxproj```

**Comment by dpogue** [comment]
This appears to be coming from vcpkg, regarding the open-source SDL engine (unrelated to Plasma's SDL system).
Possibly the same issue as https://github.com/microsoft/vcpkg/issues/25818 (which was closed without any followup)

**Comment by dpogue** [comment]
We just updated vcpkg, so I'd be curious to hear if this is reproducible with a fresh clone of the repo (from within Visual Studio)

**Comment by DamnBriggsy** [comment]
A fresh clone from VS returns the same errors as before.

**Comment by dpogue** [comment]
@DamnBriggsy You tried a build again yesterday, right? Did you still have issues like this?

**Comment by DamnBriggsy** [comment]
I didn't clone from inside VS yesterday, but I tried this evening and am happy to report that the problem is resolved!
