### ISSUE TITLE
Log Drawer Colors Broken

### ISSUE THREAD

**Issue by Hoikas** [H-uru/Plasma#1355]
Only Cyan and white are displayed.

![image](https://user-images.githubusercontent.com/714455/223312945-e0bef936-40a4-4fe6-bfda-f167550ca772.png)

**Comment by dpogue** [comment]
Did this break recently? Maybe something unexpected in https://github.com/H-uru/Plasma/pull/1341?

**Comment by Hoikas** [comment]
That was my thought. I don't see anything sus in the PR, though.

**Comment by dgelessus** [comment]
Twas I, indeed.

`plDebugText::DrawString` has multiple somewhat incompatible overloads, one taking `const char *` and two taking `ST::string`. The arguments after the string are different, but not different enough to cause a compiler error, so the switch to `ST::string` silently caused the wrong overload to be called.

![`plDebugText::DrawString` overloads](https://user-images.githubusercontent.com/6641959/223543800-7a23a044-fa64-44eb-a0a3-d291ba92df1b.png)

Switching it to `DrawString_TEMP` seems to fix it. I'll check if perhaps some other places are affected as well and then submit a fix.
