### ISSUE TITLE
Journal text rendering broken for non-English languages

### ISSUE THREAD

**Issue by dgelessus** [H-uru/Plasma#1403]
Originally discovered here: https://github.com/H-uru/moul-assets/pull/237#pullrequestreview-1489103395

Several journals render badly in non-English languages. At some point after a non-ASCII character appears, the text stops rendering until the end of the current double page. The following pages sometimes work, sometimes they're partially broken too, and sometimes also completely blank. Sometimes a page renders partially at first, but then turns blank after flipping back and forth a few times.

This affects at least the credits journal, Yeesha's book for the pillar ages on the Relto bookshelf, and the KI/Nexus notebook in the hood classroom. I've reproduced this with French, German, and Russian.

How it's supposed to look in German - with Gehn 1.28, based on 2f1c126ee583dc82768259ebf5d3520d4535ddaf from 2021-04-09:

![German credits journal, working](https://github.com/H-uru/Plasma/assets/6641959/8dfa2395-c785-40d9-8d1e-78e4fd31d9fa)

How it looks right now - with 730d2a3d66f230f7c5000d6f8cf55f0cb1c9cb00 from 2023-06-21 and H-uru/moul-assets@08f4fdfbd9421867256ae8c7599b0ea657382f95 from 2023-05-17:

![German credits journal, broken](https://github.com/H-uru/Plasma/assets/6641959/e34ef022-380d-4d67-a34b-84103a43d306)

I have no idea yet what causes this bug or when it was introduced (other than "sometime in the last two years").

**Comment by dgelessus** [comment]
@dpogue [mentions](https://github.com/H-uru/moul-assets/pull/237#issuecomment-1603352573):

> IIRC this came up in testing of Kalamee's credits journal translation too (on an OU client, I think?)

**Comment by dpogue** [comment]
The discussion about the Kalamee journal is here(ish): https://discord.com/channels/282045216221822978/1053344855876714537/1114318208560807956

Since @DoobesURU was testing it, I'm going to venture that it was more likely a H'uru client.

**Comment by dgelessus** [comment]
Narrowing down the timespan a bit: 8b27f1ec085ac411bfab8668685a2ac655b9c7d9 (2023-01-02) was still working, whereas d09814fd296b75be5af3675e953ffaa636ad7488 (2023-03-04) already has the bug.

**Comment by dpogue** [comment]
oh good, that is a _much_ more reasonable time period to try to bisect 😅

**Comment by dgelessus** [comment]
273e662d705452b10fb3c24bdea6b7092983c533 (2023-02-06) good, c49ec0841b02eec8ffff00b61d23669a7aff9f9b (2023-02-19) bad. Guessing I broke it in #1316. So much for "Improve Unicode support" 🙃

**Comment by dpogue** [comment]
Previously it was using `wchar_t` for a bunch of stepping through strings and character comparisons. In theory the change to `char` should be safe, but that would be my first suspicion given that this bug appears to only affect non-English text.

**Comment by dgelessus** [comment]
It was indeed #1316. Result of `git bisect`:

> There are only 'skip'ped commits left to test.
> The first bad commit could be any of:
> 53a706ad7db1db84da8ded5227bdc02575dc66c1
> 8efde951d1296951ccf686529db19e2f743f486f
> 4d866dbe28b6a745ddac349dd95a5a2a11022a05
> d4cff0b3c368c321ab8fb3594f9055944d08afeb
> 42d8d1549ea61448ccad74113ae412daa4429826
> We cannot bisect more!

The skipped commits are because I introduced a crash there and only noticed and fixed it a few commits later. That part is probably worth looking at... (I'm done for tonight though)
