### ISSUE TITLE
PlasmaMax footstep sounds are garbled unicode

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#1435]
![plasmamax-footsteps](https://github.com/H-uru/Plasma/assets/241708/433509fc-4e2e-4610-b1b4-20a058d0513a)

**Comment by Deledrius** [comment]
I just noticed what appears to be garbled Unicode in the string fields of PFMs a couple of days ago.  Are you seeing that as well?

**Comment by dgelessus** [comment]
Yali reports in the OpenUru Discord:

> it's still in Chinese
> ...and Max just crashed

Looking over Hoikas' changes again, I don't see how though... `ComboBox_AddString` makes a copy of the string, right?
