### ISSUE TITLE
Teledahn buckets are glitchy/broken if stopped after running

### ISSUE THREAD

**Issue by dgelessus** [H-uru/Plasma#1479]
To reproduce:

1. Play with a H'uru client on DIRTSAND, e. g. TrollLand. I also tested this with a locally built client and my own DIRTSAND instance. Not sure if this is server-dependent.
2. Link to a fresh instance of Teledahn.
3. Turn on the power and start the bucket train, but *don't* jump into the bucket.
4. Stop the buckets so that one of them lines up with the "entry point" again. (If you have trouble with the timing: activate the bucket lever shortly after a bucket passes the post *before* the "entry point".)
5. Jump into the bucket, possibly after pulling the lever again to restart the bucket train.

After this point, the bucket train glitches out in various ways, often making the puzzle impossible to complete. Glitches I've observed so far:

* It's impossible to jump into the bucket.
* Jumping into the bucket only works if you manually click on the bucket, not if you simply approach the bent part of the railing.
* After jumping into a stopped bucket, it's impossible to get back out, either with the movement keys or by clicking the hotspot outside the bucket.
* After pulling the lever and then jumping into the bucket, the bucket train never starts.
* After jumping into a bucket, the camera glides over to a different bucket farther up the train.
* During the bucket ride, the camera glides to various places that are nowhere near the bucket train.
* Some of the buckets become detached from their wheel thing (bogie?) and move along the cable independently (but at the same speed). I'm not sure if this is related or a general glitch.

While debugging this, I also noticed that the bucket train causes *a lot* of network messages in certain cases. Not sure if these are related to the glitches.

* When a bucket reaches any of the "special points" along the cable, the client sends lots of repeated `plNotifyMsg`s (plus TestAndSet messages) for tldnBucketBrain.py. You can see this in network.log.
* As long as a bucket is at the "entry point", the SDL variable `tldnBucketAtEntry` flips back and forth between -1 and the correct bucket number, multiple times per second. If the bucket train is running, this only happens for a short time, but if a bucket is stopped at the "entry point", this happens constantly, until you link out and back in. You can see this in OLD_ASYNC_LOG.log and in the debug output (when running plClient with a debugger).

Possibly related: #962

**Comment by DamnBriggsy** [comment]
I'm not 100% sure if this is connected, but Maurus noticed an issue with Zandi today and dgelessus noticed some similarities. In the cleft, Zandi will no longer speak to you when you approach. If you exit his region, we will start to see a huge flood of messages in network.log. This happens on both dirtsand and MOSS (minkata alpha shard), provided you are using the modern H'uru client. network.0.log attached.

[network.0.log](https://github.com/H-uru/Plasma/files/12897477/network.0.log)

**Comment by dgelessus** [comment]
@Mirphak reminded me that he has a similar problem with excessive network messages spamming the network log (although that one only occurs in multiplayer). He tracked his problem down to #1429. Reverting that PR also fixes the issues I described here, so it seems that all of these problems have the same cause.

The actual commit that causes it is 4ef380f10fef7523761c73bc4cb2aeec68fac6fd, but even knowing that, this will be difficult to figure out. I'm guessing the removal of the implicit conversion changed *something* in a way that still compiles, but no longer behaves as it should.
