### ISSUE TITLE
Nexus not displaying names of ages

### ISSUE THREAD

**Issue by Hazado** [H-uru/Plasma#1491]
This is using the latest client and python files.
No errors in my python log
![image](https://github.com/H-uru/Plasma/assets/416114/7a545efb-923b-44bf-94ce-5af38403ddab)

**Comment by Hazado** [comment]
Duplicate issue - https://github.com/H-uru/Plasma/issues/1493

**Comment by Mirphak** [comment]
Same problem as in PR#1493,  easy to correct typos in GlogalEnglish.loc
