### ISSUE TITLE
KI not showing age name for some ages

### ISSUE THREAD

**Issue by Hazado** [H-uru/Plasma#1493]
Nexus and my neighborhood name doesnt show up
Going to Chiso Preniv, the name showed up

![image](https://github.com/H-uru/Plasma/assets/416114/39573cab-ab5f-4139-b353-26d8854244c2)

**Comment by dgelessus** [comment]
On which shard is this? The displayed age name is primarily a server-side thing (stored in the vault) as far as I know.

**Comment by Hazado** [comment]
This is MOULa, the cyan official shard

**Comment by Mirphak** [comment]
A typo has been corrected in H-uru xLocTools.py
PtGetLocalizedString("Global.Formats.Possessive", [possessorName, possessionName])

But not in Global*.loc
			<element name="Possessive">
				<translation language="English">%1s's %2s</translation>
			</element>

**Comment by Mirphak** [comment]
In GlobalEnglish.loc it should be 
element name="Possessive"

**Comment by Hazado** [comment]
Okay so probably want to put the typo back into xLocTools.py so it knows where to get the correct loc

**Comment by dgelessus** [comment]
This is a data file mismatch. In the H'uru moul-assets repo, it's spelled as the H'uru Plasma client expects it:

https://github.com/H-uru/moul-assets/blob/b50321da8ecdb9aab56eab55ceb50c677b9f96e7/compiled/dat/GlobalEnglish.loc#L182-L184

But the GlobalEnglish.loc served by Cyan's shard still says `Possesive`, which is the spelling expected by the OpenUru client that Cyan ships.

As I understand it, H'uru is no longer aiming to make the mainline Plasma client fully compatible with Cyan's MOULa dataset, so I don't think this is considered a bug.

**Comment by Hazado** [comment]
Understand, closing the issue.
Thank you @Mirphak for helping me figure out what I did wrong :)
