### ISSUE TITLE
Commit 93d8c2c broke CMake on VS  17.9.5

### ISSUE THREAD

**Issue by trebonian** [H-uru/Plasma#1577]
I updated Visual Studio to 17.9.5 (Free version) - and also did a pull on this repository - so I don't know for sure if the the older 17.9.4 works with the new vcpkg.

I reverted this commit and everything rebuilds ok.

The error I get when I run with the commit in is:

![image](https://github.com/H-uru/Plasma/assets/11244/c1227014-0f56-4987-ab3c-3b5a934d5ff0)

![image](https://github.com/H-uru/Plasma/assets/11244/37f55eab-c0d1-43ae-91c2-6d4db9165373)

I think I need to do some VS magic to update the "vcpkg" submodule in my local repo. I am not sure how to do this.

Let me know if there is more that I can capture if you can't reproduce this

**Comment by trebonian** [comment]
I figured out how to do a "git submodule update" inside the VS Project. This fixed the issue...

**Comment by dpogue** [comment]
Hmm, we have code in CMake to setup the submodules if they don't exist, but nothing to bring them up to date if they're not. I'm not sure if there's even a good way to detect that situation and warn about it... 🤔

Glad to hear you got it working!

**Comment by trebonian** [comment]
All I had to do was clone into an empty repo, and stop it after git.exe was in the new environment.

I then set the path to the new git.exe and ran “git submodule update” when my current directory was the original Plasma.

I suspect that you could run it in place but it might wipe itself out when the update is done

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
