### ISSUE TITLE
Teledahn walkway problem

### ISSUE THREAD

**Issue by Filtik** [H-uru/Plasma#1582]
Hi,
I may have found a problem.
With a newly created client, Teledahn cannot get through on the Walkway.
This works with an old client.
The red box hinders getting through. On the old client this is a U shape.
Here are a few pictures about it

New client:
<img width="962" alt="2024-04-08 20_27_06-The Open Cave" src="https://github.com/H-uru/Plasma/assets/1388865/0ad4dde6-76e1-4614-a83b-f90254d93df7">
<img width="962" alt="2024-04-08 20_27_43-The Open Cave" src="https://github.com/H-uru/Plasma/assets/1388865/fba4e3b2-cf59-4cdb-8f1a-a6415a9bed49">

Old client:
<img width="962" alt="2024-04-08 20_36_40-The Open Cave" src="https://github.com/H-uru/Plasma/assets/1388865/5551417c-e0ed-4939-b2f9-6d4892389999">
<img width="962" alt="2024-04-08 20_37_10-The Open Cave" src="https://github.com/H-uru/Plasma/assets/1388865/dc659623-9c01-4735-a062-e4fbd350743b">

**Comment by Hoikas** [comment]
Are you using the latest Teledahn PRP files from H-uru/moul-assets? It looks like https://github.com/H-uru/moul-assets/commit/d062f314da70165b82e39b6c9a46239979df4e8c should have fixed this.

**Comment by Filtik** [comment]
Thank you very much, I tested it with the current MOULa PRPs and with old PRPs. It works with the ones you linked.
