### ISSUE TITLE
[macOS] Caps Lock does not turn on running

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#1599]
Turning <kbd>Caps Lock</kbd> on and off does not affect the movement speed on macOS. Holding <kbd>Shift</kbd> to run works fine.

The bit of extra complexity here is detecting the caps lock state on startup, and monitoring for changes to caps lock state while Uru does not have focus, but it seems like Cocoa events provide ways to do that.

**Comment by colincornaby** [comment]
I'll take a look.

This also reminds me that there is an open question of optionally adopting the Game Controller framework on newer versions - which provides a more sane interface for games to get keyboard input. This would also be required for iOS/visionOS.

We'd need this code path for older macOS versions though. So I'll look at patching this path.

**Comment by dpogue** [comment]
The fix in #1601 works well enough for me to consider this closed.
