### ISSUE TITLE
3dsMax 2020 Python settings can't scroll

### ISSUE THREAD

**Issue by Filtik** [H-uru/Plasma#1613]
Hello, I'm using 3DS Max 2020 and wanted to adjust my Python settings. 
Unfortunately I can't scroll or go down in any other way.

<img width="233" alt="2024-09-29 13_41_39-" src="https://github.com/user-attachments/assets/7415c506-16d0-48fc-bfc5-569f5dfa8574">

**Comment by Hoikas** [comment]
Unfortunately, I do not have access to 3ds Max 2020. However, I did check 3ds Max 2022 and found that the Python File rollout scrolls correctly on this edition of 3ds Max and the current plugin.
![image](https://github.com/user-attachments/assets/df078bc0-31ac-4a6f-bf72-46936d5dba57)

**Comment by dpogue** [comment]
I do feel like we've had scrolling issues with this dialog in particular before... See https://github.com/H-uru/Plasma/commit/107af8272d8bfa9200c27017bd4d5439da9b8097 and https://github.com/H-uru/Plasma/commit/8b05d663c31437c010adbf18003112ecb4bb163b

Maybe the fix in that second commit that scopes it to 2022+ needs to be relaxed to 2020?

**Comment by Hoikas** [comment]
I think that's reasonable. It would be really nice if we could figure out where the UI changed to the current weird amalgamation of Win32 and Qt.

**Comment by dpogue** [comment]
Qt was first introduced (optionally) in Max 2017, but it looks like Max 2020 might be where/when it was more officially integrated.
