### ISSUE TITLE
Certain Triggers appear to have been broken by a Plasma update

### ISSUE THREAD

**Issue by patmauro** [H-uru/Plasma#1641]
A Plasma update from sometime within the last year or so seems to have broken a couple key "triggers" for doors, etc. Confirmed by loading up a legacy Huru client (Edit: 814a6ac) from ~~a few years back~~ June 28 2023 and testing the same issues. This seems to mainly affect things built in Korman, and can be most notably witnessed with Chiso Preniv's secret door trigger: clicking the button will cause the clickable target to vanish and nothing happens. We're not sure _which_ specific Plasma change broke these triggers, but it seems to have been something within the last 1 - 1.5 years or so.

Specific behaviors as noted by @Traveler263 -

> 1. Animated Up/Down Physics Object on a Single Button Trigger that toggles between states.
> 2. Animated Sliding Door left/right on two button Triggers
> 3. Journey Door in the style of NB01 classroom door, single button trigger, to open with an exiting region to close.
> 
> In cases 1 and 2, they are set to their visual 'closed' and 'raised' states upon loading into the age, where upon trying to trigger the opening for 1 and 2 plays the animation from 'open' to 'closed' or 'lowered' to 'raised.' Afterwards, operating them works as normal. Toggle again to 'open'/'lower', toggle again to 'close'/'raise'.
> 
> In case 3, it is a bit different - If I immediately enter the 'close on exit' region, and try to 'open' the door, the entire journey door setup breaks. no amount of pressing will cause it to function again, forcing a reload of the age. However, if I enter the 'close on exit region', then exit the region, the door will immediately play its 'closing' animation. Afterwards, pressing the open button triggers it opening properly.

The Chiso Preniv example I noted above falls into "Type 3" here, and since it has no specific "close on exit" region, it means attempting to open the door will simply break the door entirely as noted here. On a legacy version of the huru client from roughly 2 years ago, everything works fine - even if I plug in a newer version of chiso.

Note: While it's true that "fan ages" are not being accepted into Huru currently, I would not categorize this as a "fan age issue" - creating a "starting" point on top of which a shard can be created _is_ a stated goal of the repo, so continued interoperability with korman-built ages does seem like something worth pursuing as an issue to fix here. Plus, it would probably be good to have this already worked out in advance of any upcoming tests to ingest h'uru's plasma changes into the new nextGen client for OU. It's possible this is something that could be addressed from the Korman side, but since it seems like there is a specific change on the Plasma side that caused this breakdown, it felt appropriate to post this ticket here.

CC @Traveler263 @ametist365

**Comment by patmauro** [comment]
Additional info: Confirmed the older build this works correctly on was as of Commit 814a6ac on June 28, 2023: https://github.com/H-uru/Plasma/commit/814a6ac

**Comment by Hoikas** [comment]
> notably witnessed with Chiso Preniv's secret door trigger: clicking the button will cause the clickable target to vanish and nothing happens. 

The secret door button appears to function correctly for me on 76e31fe3f8b930fc0dd7a2b5e31985a0188e59e8

**Comment by Hoikas** [comment]
After some research, it appears that there are two separate issues that were happening here.
 - ReischuApartment had an SDL variable that begins with a numeric character, which DirtSand did not appreciate, causing it to toss the entire ReischueApartment STATEDESC. We should probably evaluate whether or not these are legal in the client and update DS if they are.
 - Destiny seems to be either missing the Chiso SDL file or be using a much older copy of the Chiso SDL, which lacks the variable for the secret door button. Older scripts seem to tolerate this but newer scripts do not. Client data and servers with matching SDL files do not seem to exhibit any problem.

**Comment by patmauro** [comment]
Yep - evidence looks solid here, and seems to explain everything we've been seeing. You can understand why I initially thought these might be related issues (and why these issues might be plasma-specific) but I'm just glad to have explanations for this behavior either way. Thanks so much for your help narrowing this down for us @Hoikas.

Seems like we can safely close this ticket now - any followup items here worth keeping this one open for?

**Comment by patmauro** [comment]
Closing this one as we have confirmed this is _not_ a Plasma issue and have managed to resolve/solve the underlying issues here. Will document the follow-up item to evaluate whether these are legal client-side as a follow-up Issue.
