### ISSUE TITLE
Make Plasma 64-bit compliant

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#34]
This likely requires changing almost every function to verify that it will work properly when compiled in 64-bit.

**Comment by Deledrius** [comment]
The lack of a 64-bit PhysX is also going to bite us here.  With just a few tweaks to update Windows API calls I can get the entire solution (excluding the Max plugin) building for 64-bit except plPhysX.  Until we replace that (#4), we can't even _build_ a client.
