### ISSUE TITLE
Cross-Platform Physics Library

### ISSUE THREAD

**Issue by branan** [H-uru/Plasma#4]
Bullet is cross-platform and has a license compatible with Cyan's GPLV3. I also have experience with it.

**Comment by Deledrius** [comment]
As discussed in #578, we have finally arrived at a situation where we may possibly be able to update at least to a contemporary version of PhysX.  Replacing the cooked data in the PRPs with uncooked data should remove the major stumbling block for both updating PhysX as well as moving to another physics engine entirely.

**Comment by Hoikas** [comment]
These two threads should be consolidated -- either this issue or #578 should be closed for the sake of de-duplication and better issue management.

**Comment by Deledrius** [comment]
I believe #578 should be closed and discussion focused here, on updating the Physics engine generally.
