### ISSUE TITLE
Use LZMA compression for downloading from FileSrv

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#53]
I believe right now it uses .gz files with plZlibStream. 7zip offers better compression, especially if we can combine multiple files into a single archive.

Future ideas based on this support:
- Compression of Python and SDL downloaded from server. Download a single archive that unpacks to the required multiple files.
- Manifest-based archives. Rather than downloading each file, you could download all the files for an Age as a single archive.

**Comment by zrax** [comment]
An ancient issue, but something else to consider here is algorithm performance.  LZMA offers better compression, but requires significantly more processing power to compress and decompress.  On the other hand, something like zstd offers slightly better compression than zlib, but with notably better decompress speed, and lz4 offers slightly worse compression but with massively improved speed.

**Comment by Hoikas** [comment]
With some of the dinosaurs folks play URU on, decompress speed should be considered the most important metric IMO. Considering the results of zlib compression on the assets (it's pretty good), I'm not even sure investing time into a new algorithm (and properly supporting backwards compatibility with old client/servers) is particularly desirable.

**Comment by dgelessus** [comment]
(see also #737)
