### ISSUE TITLE
CMake error: string_theory

### ISSUE THREAD

**Issue by mclayan** [H-uru/Plasma#535]
I was trying to configure via CMake but I got this error:
```
CPUID header found -- using hardware math acceleration when available
CMake Error at lib/cmake/string_theory/string_theory-targets.cmake:64 (message):
  The imported target "string_theory" references the file

     "D:/Libraries/VC++2013/x86/lib/string_theory.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "F:/Projects/cpp/cwe/plasma/lib/cmake/string_theory/string_theory-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  lib/cmake/string_theory/string_theory-config.cmake:25 (include)
  CMakeLists.txt:46 (find_package)


Configuring incomplete, errors occurred!
See also "F:/Projects/cpp/cwe/plasma/CMakeFiles/CMakeOutput.log".
```
I looked up string_theory-targets.cmake and saw this:
```
# The installation prefix configured by this project.
set(_IMPORT_PREFIX "D:/Libraries/VC++2013/x86")


# Create imported target string_theory
add_library(string_theory STATIC IMPORTED)
```
I don't know what CMake expects me to do as I'm not very familiar with big software projects (just trying to learn from you code).

**Comment by zrax** [comment]
This bit is suspicious:
`"F:/Projects/cpp/cwe/plasma/lib/cmake/string_theory/string_theory-targets.cmake"`
especially with the recent change to avoid using the CMake package registry in string_theory 1.2.  If you recently udpated string_theory, I'd recommend clearing anything in the CMake package registry.  Specifically in Windows, this would mean deleting the key `HKEY_CURRENT_USER\Software\Kitware\CMake\Packages\string_theory` from within regedit.

Another suggestion if the above doesn't help is to remove any string_theory files from your install dir, and rebuild the INSTALL target to reinstall fresh copies.  Note that debug and release targets will install different file names (string_theoryd.lib vs string_theory.lib), so be sure to build and install both targets if you intend to work with both in Plasma.

**Comment by Deledrius** [comment]
@mclayan Have you had any luck getting this to build?  There have been quite a few fixes in the last week or so that might make it worth updating and trying again.

If you want additional help, feel free to drop into the IRC channel #writers on irc.guildofwriters.org.

**Comment by mclayan** [comment]
No, it still doesn't work using the devlibs.zip bundle: 
```
CPUID header found -- using hardware math acceleration when available
CMake Error at lib/cmake/string_theory/string_theory-targets.cmake:64 (message):
  The imported target "string_theory" references the file

     "D:/Libraries/VC++2013/x86/lib/string_theory.lib"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "F:/Projects/cpp/cwe/new/plasma-git/lib/cmake/string_theory/string_theory-targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  lib/cmake/string_theory/string_theory-config.cmake:25 (include)
  CMakeLists.txt:46 (find_package)


Configuring incomplete, errors occurred!
See also "F:/Projects/cpp/cwe/new/plasma-git/CMakeFiles/CMakeOutput.log".
```

I tried cloning and building string_theory on my own, worked well, CMake accepted the path while configuring CWE but while building, all additional include directories were wrong. I could change them in VS by hand for every build item but this would cost me much time (I'm sure there is somewhere an option to add the right paths to the whole solution but I'm not experienced enough to find it). What's causing me problems:
`#include <string_theory/formatter>` looks here for the file: `F:\Projects\cpp\string_theory` but should be: `F:\Projects\cpp\string_theory\include`. And this goes for all references regarding string_theory.

**Comment by zrax** [comment]
It looks like string_theory is including absolute paths to libraries in the generated cmake files.  I'm currently working on fixing that.

**Comment by zrax** [comment]
This should be fixed by zrax/string_theory@d6b4d42e (soon to be released in string_theory 1.4)

**Comment by mclayan** [comment]
Thanks!

**Comment by Deledrius** [comment]
Everything building for you now, @mclayan? 😄

**Comment by mclayan** [comment]
@Deledrius currently trying 😄

**Comment by mclayan** [comment]
@Deledrius Yes, works all well 😄

**Comment by Deledrius** [comment]
Excellent!  I saw you popped into IRC, but I was AFK at the time.  If you have any further questions, please don't hesitate to stop by again.  Enjoy!
