### ISSUE TITLE
Patcher needs data-consistency improvements

### ISSUE THREAD

**Issue by Deledrius** [H-uru/Plasma#550]
Currently the patcher allows the user to cancel the initial Cyan data download, which will then attempt to run a (doomed) normal Gehn patch process upon next invocation.

I see two possible improvements, one simple and one advanced:

- Simple: Warn the user, if they choose to close the patcher when performing an initial install, that they will need to run the repair install again before continuing.  The user can fail to heed this warning, but at least we tried.
- Advanced: Assume that the full repair should be run unless an `imagecomplete` value is set in our INI store (or wherever deemed appropriate).  This value is only set upon a successful, complete game image download.  If the patcher is run without the repair option and this value is not found, it should relaunch in repair mode automatically.  This would transparently cover both user-error and connection issue problems.

This issue was highlighted in the discussion in the "Gehn on OSX" thread, particularly these posts:
https://forum.guildofwriters.org/viewtopic.php?p=71282#p71282
https://forum.guildofwriters.org/viewtopic.php?p=71285#p71285

**Comment by Hoikas** [comment]
With the recent decision by Cyan to allow redistribution, I believe this can be closed?

**Comment by Deledrius** [comment]
I agree.  This problem vanishes if we can provide a complete fileserver.
