### ISSUE TITLE
Tests won't build in VS2017

### ISSUE THREAD

**Issue by Deledrius** [H-uru/Plasma#556]
Attempting to build the gtest projects in VS2017 results in a failure: `warning treated as error - no 'object' file generated`.  There does not appear to be a newer release than the currently-used 1.8.0, but updating to the gtest master fixes the issue and allows the tests to compile.  It seems likely that https://github.com/google/googletest/commit/2641b021fc2ab12896cf868d90f19936ef4b4696 is needed.

**Comment by zrax** [comment]
This was needed for string_theory (zrax/string_theory@2c49e9ce353dd04bd1837c614ec7db7faf53e1f2), so it makes sense it's needed here too.

**Comment by Deledrius** [comment]
Any preference on how to solve this?  They haven't tagged or released a version since the initial 1.8.0, which is too far back to include the fix.
