### ISSUE TITLE
Keeps asking to install Physx on wine 

### ISSUE THREAD

**Issue by jamie-marchant** [H-uru/Plasma#568]
Both the internal H-Uru client and Gehn Shard, give me a problem when I try to run them on Wine under Linux. They keep asking me to install PhysX even though the correct version of PhysX is already installed. Could someone please look into this. My problem may indicate an issue that could affect some Windows installstaitonts.

**Comment by Deledrius** [comment]
I haven't seen this behavior, but it's been a little while since I last tried running it under Wine.  Which version of Wine are you using?

**Comment by jamie-marchant** [comment]
I have Wine-3.5

**Comment by Lunanne** [comment]
I have tried replicating the issue but I have so far not succeeded. 
Wine 3.5 isn't easily available for download right now, so I used PlayOnLinux with Wine 3.5 32 bit. I saw some errors during the initial install but everything seems to be working fine and I was not asked to install Physx on relaunch. 

Using : 
Wine 3.5 32 bit
PlayOnLinux 4.2.12
Ubuntu 18.04

**Comment by jamie-marchant** [comment]
I have to head out soon but I will try PlayOnLinux tommrow.

**Comment by jamie-marchant** [comment]
The Gehn shard works with "PlayOnLinux" I imagine other versions of H-URU would work as well :).

**Comment by Deledrius** [comment]
Thanks for the update, @jamie-marchant!  We should look at formalizing Korovev's scripts for use as official Linux installers.
