### ISSUE TITLE
S_T 3.0

### ISSUE THREAD

**Issue by Hoikas** [H-uru/Plasma#620]
When using string_theory 3.0, the following issues are observed:
- Date fields in the KI are all displayed as "37m/37d/37y". I suspect the issue lies in `pfLocalizedString` applying arguments using `ST::stringstream`.
- Logging into MOULa with the bugged SHA0 algo returns an "Incorrect Password" error.

Builds using string_theory 2.4 are unaffected.

**Comment by zrax** [comment]
Are these fixed with string_theory master as of today's latest fixes?

**Comment by Hoikas** [comment]
Yes, the latest string_theory master and #621 allow me to log into MOULa and correctly view dates in the Big KI.

**Comment by zrax** [comment]
I'm going to mark this closed with string_theory 3.1 (just released) then.
