### ISSUE TITLE
Uninitialized Audio System leads to crashes

### ISSUE THREAD

**Issue by Hoikas** [H-uru/Plasma#673]
If the audio system is not initialized, for example by audio.ini including `Audio.Initialize false`, then playing the intro video crashes the client. [See report](https://forum.guildofwriters.org/viewtopic.php?p=74454#p74454) on the forum.

**Comment by dpogue** [comment]
I noticed this with plGLClient, where I don't have the console set up yet. It seems a bit weird to rely on `Audio.Initialize` being called via an init file instead of in the application.

**Comment by Hoikas** [comment]
Yes, I think the real fix here is to outright remove `Audio.Initialize`

**Comment by Hoikas** [comment]
In my testing, this is no longer a problem. Maybe fixed by #596?
