### ISSUE TITLE
Readme needs to be updated

### ISSUE THREAD

**Issue by EidamirZoe** [H-uru/Plasma#707]
Not sure if it should be posted in issues or pull requests, but since I did not understood how to post in pull requests (I'm new to github), I'm doing it here.
In my first attempts to build the client by myself for the first time I encountered a few issues.
I managed to do it in the end with some help and one of the issues is solved already but there are things in the Readme that need to be updated:
Tere are 2 issues there:
1.- Under the "To configure manually with CMake and build:" section, line 6 say: "Set the CMAKE_INSTALL_PREFIX option under CMAKE to the cwe-prefix folder that you extracted from the development libraries bundle." There is no cwe-prefix folder in the devlibs anymore, so this needs to be changed.
2.- Under the "Running Instructions" section, line 2 say: "Copy the Python and SDL folders from Scripts into the MOUL-OS folder, as well as the files in dat into the existing dat folder." The location is wrong, since the 3 folders are in the bin folder.
So I think the Readme need to be updated.

**Comment by Deledrius** [comment]
This is the correct place!  

Thank you for reporting these errors.  We'll work on updating this soon.
