### ISSUE TITLE
Can't take screenshot of documents

### ISSUE THREAD

**Issue by eksynn** [H-uru/Plasma#765]
![SPOILER_KIimage0013](https://user-images.githubusercontent.com/187128/103325804-51575500-4a02-11eb-81af-fc94044fe753.png)

there's an issue where screenshots of documents don't fit the whole screen (see image ⇑)

**Comment by Deledrius** [comment]
Thanks for reporting this bug!  I've confirmed that it does appear that the GUI elements are not being properly scaled with the rest of the screen for the KI screengrab.

**Comment by Deledrius** [comment]
@eksynn, This has been fixed and will hopefully be available in the not-too-distant future for players.  Thanks again for bug the report!
