### ISSUE TITLE
KI Chat subtitles/transcripts for in-game speeches

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#766]
There are a handful of NPC speeches in the game (Yeesha in the Cleft, Yeesha voiceovers in the Bahro Caves, Zandi in the Cleft) with no text alternative available.

One option is to do something like Myst V and have a dedicated subtitle system that displays a banner during the speeches with their text content, but an easier (and perhaps more in-character) option would be to display lines of dialog as KI chat as they are spoken.

I suspect this would need subtitle text and timings, and probably some additional Python scripting and changes to the existing speech triggers, but it might be possible without significant new engine functionality.

**Comment by Deledrius** [comment]
For the sake of consistency, and the fact that we have that reference, I'd prefer a system that works similarly to Myst V's if possible.  It's already localization-friendly, and it means future compatibility with Myst V content (if ever possible).

A KI chat system would probably end up needing to re-implement so much of those features that it won't be nearly as effort-saving as it seems.

I also think that most subtitles make more sense being non-diegetic, so the KI is not an appropriate place for them if the character isn't typing/sending their message.

**Comment by Hoikas** [comment]
IMO it will be much easier to code a system that dispatches local KI chat messages at a certain trigger time than redo all the fancy plate drawing stuff that Myst V did. Myst V's subtitles were visually displeasing IME, and it makes more sense to use the existing infrastructure.

**Comment by Deledrius** [comment]
"a system that dispatches local KI chat messages at a certain trigger time" is not the same code as "all the fancy plate drawing stuff".  Whether it's dispatching it to the KI or displaying it in plates, the majority of that data, timing, and localization is going to be needed for both.  I agree that sending it to the KI in the last step is probably simpler, but that's surely a tiny amount of the overall task.

What is it about the plates which is fancy/difficult?  What do you find visually displeasing about the subtitles in Myst V?

Another option would be to adopt a standard subtitle format, such at `.srt`.  That would allow localizers to utilize standard tools for writing/editing subtitles.  It supports the same features as the Myst V subtitles, AFAIK, and converting to it would be direct and lossless.

**Comment by Hoikas** [comment]
The text rendering looks like garbage and the whole system is out of place in Uru IMO. We already have place for text, let's use it.

**Comment by Hoikas** [comment]
Done by @ZarothYe
