### ISSUE TITLE
Plasma build fails with vcpkg bootstrap error

### ISSUE THREAD

**Issue by tallpgr** [H-uru/Plasma#787]
Attempted to build Plasma on Win10 20H2 for the first time with VS2019 16.8.3.  It failed while initializing the project with the following log entries:

`1> CMake generation started for configuration: 'x64-Debug (default)'.`
`1> Found and using vcpkg toolchain file (D:/Pkgs/vcpkg/scripts/buildsystems/vcpkg.cmake).`
`1> The toolchain file has changed (CMAKE_TOOLCHAIN_FILE).`
`1> Command line: "cmd.exe" /c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="D:/Pkgs/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g" 2>&1"`
`1> Working directory: D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g\out\build\x64-Debug (default)`
`1> [CMake] -- Bootstrapping vcpkg before install`
`1> [CMake] -- Bootstrapping vcpkg before install - failed`
`1> [CMake] CMake Error at vcpkg/scripts/buildsystems/vcpkg.cmake:682 (message):`
`1> [CMake]   vcpkg install failed.  See logs for more information:`
`1> [CMake]   D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g\out\build\x64-Debug`
`1> [CMake]   (default)\vcpkg-bootstrap.log`
`1> [CMake] Call Stack (most recent call first):`
`1> [CMake]   C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.18/Modules/CMakeDetermineSystem.cmake:93 (include)`
`1> [CMake]   CMakeLists.txt:14 (project)`
`1> [CMake] -- Configuring incomplete, errors occurred!`
`1> 'cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="D:/Pkgs/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g" 2>&1"' execution failed with error: ''cmd.exe' '/c "%SYSTEMROOT%\System32\chcp.com 65001 >NUL && "C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja"  -DCMAKE_BUILD_TYPE:STRING="Debug" -DCMAKE_INSTALL_PREFIX:PATH="D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g\out\install\x64-Debug (default)" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29333/bin/Hostx64/x64/cl.exe"  -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\COMMUNITY\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" -DCMAKE_TOOLCHAIN_FILE="D:/Pkgs/vcpkg/scripts/buildsystems/vcpkg.cmake" "D:\Users\**hidden**\Desktop\HUru-Origin\plasma.g" 2>&1"' returned with exit code: 1'.`

It looks like it may be confused by an existing VCpkg installation.  `vcpkg-bootstrap.log` was empty.

(posted as alias for rarified)

**Comment by Hoikas** [comment]
We figured this out in the OU Discord. The issue seemed to be that Cygwin's git.exe was checking out files without setting execute permissions on them, causing the vcpkg bootstrap to fail with "Access Denied."
