### ISSUE TITLE
Shroomie Gate, Inconsistent State

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#792]
via Ehren on the Guild of Writers forum: https://forum.guildofwriters.org/viewtopic.php?f=117&t=7230

> This is a glitch that exists on every MOULa server, but it just occurred to me that someone might actually care to fix it in a future version here. In Teledahn if you pull the lever to open/close the dam with the power cut off to it (either by having the main power off or the lever for the spinning shaft disengaged), the gate will appear to not move, but relinking will show its state actually did toggle despite the lack of power.
>
> In other words, having the power off merely prevents the gate from animating, and relinking or starting up the power and pulling the lever again afterwards shows that the state did in fact change. For the sake of logical consistency I think it would be worth a small fix, I can't imagine it would be too hard to do.

**Comment by Deledrius** [comment]
Nice catch!  Thanks for the bug report, Ehren!
