### ISSUE TITLE
Cursor resolution

### ISSUE THREAD

**Issue by D3B453R** [H-uru/Plasma#795]
Hey,
I don't know if it's actually an issue but when I'm compiling the client by my self the ingame cursor is way to small. :D

![Screenshot 2021-01-27 231158](https://user-images.githubusercontent.com/39367548/106061002-16296e00-60f5-11eb-9936-fdf51024590d.png)

**Comment by Deledrius** [comment]
@Hoikas, is this another HiDPI issue?

**Comment by cwalther** [comment]
It does look similar to my observations in #636, but then the size of the title bar looks like 100% scale.

**Comment by Hoikas** [comment]
Thanks for reporting this issue - we've fixed the cursor size issue. However, there still some resource rendering issues outstanding that we'll be tracking in #800.
