### ISSUE TITLE
Client Resource.dat Rendering Roundup

### ISSUE THREAD

**Issue by Hoikas** [H-uru/Plasma#800]
This is a meta-issue for tracking the outstanding issues with cursor rendering. See the discussion in #796 for more detail.

* [x] Cursor appears too small in game.
    * Reported in #795 
    * Fixed by #796
* [x] Microphone icon appears garbled.
    * Would be fixed by a bump to cairosvg 2.5.1 in #801
* [x] Cursor lacks shadows.
    * Cairosvg does not support the filter `feGaussianBlur`, a regression from rsvg
    * Fixed by #814

**Comment by cwalther** [comment]
_Cursor lacks shadows_ is addressed by #814.

Possible additional issue: `xLoading_*.png` are generated in higher resolution than they used to, years ago – e.g. 1175×1177 instead of 256×256 for `xLoading_Linking.*.png`. Check what today’s client actually expects.

**Comment by Hoikas** [comment]
This has been fixed for awhile. Closing.
