### ISSUE TITLE
Skip the intro videos if running with `/Age`

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#910]
I know the workaround is to just delete or rename the video file and it will happily skip over it, but it would be nice to not need to do that.

IIRC there's some sort of boolean for whether the skip the video or not, and I had hooked that up in plGLClient to skip the video when `--Age` was specified but the init process for plClient is a bit more complicated due to the login dialogs.

**Comment by Hoikas** [comment]
IMO, it would be better to add a new option (eg `/NoLogo`) for skipping the intro videos.
