### ISSUE TITLE
MOULa: Imager Upload Crash (self)

### ISSUE THREAD

**Issue by DamnBriggsy** [H-uru/Plasma#918]
When using the H'uru client on MOULa, attempting to upload pictures to an imager will result in a crash to desktop. Python.log reports:
```(05/28 09:26:33) KIHandler - Traceback (most recent call last):
(05/28 09:26:33)   File "./python\ki\__init__.py", line 1274, in OnVaultEvent
(05/28 09:26:33)     PtDebugPrint("xKI.VaultEvent(): Event = {} and data = {}.".format(event, tupData), level=kDebugDumpLevel)
(05/28 09:26:33) RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Comment by Hoikas** [comment]
Unfortunately, I am unable to reproduce this issue.

**Comment by DamnBriggsy** [comment]
After rebuilding the client and grabbing updated files from MOULa, I am still encountering this issue.

**Comment by DamnBriggsy** [comment]
I am no longer encountering this issue, I have no explanation. Glad it's working, though!
