### ISSUE TITLE
Max lightmapgen crashes on animation-only files

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#934]
The workaround is to uncheck the "Generate lightmaps" checkbox on the export panel.

It crashes in `plRenderGlobalContext::MakeRenderInstances` where fInstList is null.

**Comment by Hoikas** [comment]
Is there an already existing max file that exhibits this issue?

**Comment by dpogue** [comment]
Try any of the Kahlo Critter animations (although they need a bit of editing to use PageInfo components). The avatar wave animations might have the same issue?

**Comment by dpogue** [comment]
[Example 3DS Max 7 file](https://drive.google.com/file/d/1Yio0Ja4b0hjenk8YA12LHaFgmdShlCHM/view)
