### ISSUE TITLE
Update gtest submodule to 1.11.0

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#946]
The current gtest version is causing compiler errors on Linux with clang 12.

https://github.com/google/googletest/releases/tag/release-1.11.0

**Comment by Hoikas** [comment]
I feel like we should probably move to using the [vcpkg gtest port](https://github.com/microsoft/vcpkg/tree/master/ports/gtest) and [CMake's FindGTest](https://cmake.org/cmake/help/latest/module/FindGTest.html) instead of having a submodule for this.

**Comment by zrax** [comment]
> 
> 
> I feel like we should probably move to using the [vcpkg gtest port](https://github.com/microsoft/vcpkg/tree/master/ports/gtest) and [CMake's FindGTest](https://cmake.org/cmake/help/latest/module/FindGTest.html) instead of having a submodule for this.

Although it's possible to use an external GTest, it is designed to be used as a submodule (and Google recommends using it that way).  Unless there's a really good reason to switch, I think we should keep using it the way it's designed to be used.
