### ISSUE TITLE
Chat fade timer triggers while user has unsubmitted text

### ISSUE THREAD

**Issue by Alderem** [H-uru/Plasma#959]
The chat fade timer doesn't renew when the user is typing a long string of text, so it can trigger and fade out when the user is still typing.  Worse, typing more doesn't un-fade the text, so then you're typing blind.

Couple of ways this could be fixed:
 Option 1:  The chat fade timer should reset whenever the user presses a key (to enter a character or backspace), and chat should unfade if the user types when it is faded.
 Option 2 (my preferred): The chat fade timer should simply not count down when the user has unsubmitted text.  Only fade out if the user doesn't have text on the line.

**Comment by dpogue** [comment]
:+1: for option 2

**Comment by Hoikas** [comment]
I think this issue is worse on the OU codebase, but we do still have at least one repro of it in our codebase. To repro, open the Big KI. Close the Big KI and immediately type a few characters. Stop. Watch the text fade out.

**Comment by Hoikas** [comment]
I believe #1030 (thanks to @ZarothYe) fixes the last remaining incident of this in our client. MOULa/OU/legacy clients may have other problems, though. If this continues to be a problem on master, we can reopen this issue.
