### ISSUE TITLE
Bahro doors can be opened by non-owners who have finished age even though owner hasn't finished the age

### ISSUE THREAD

**Issue by bertvandepoel** [H-uru/Plasma#964]
I noticed I was able to open my friend's Teledahn Bahro door even though he still had two journeys to go. That seems like a bug, but possible a very difficult one to solve.

**Comment by Hoikas** [comment]
Maybe others have different opinions, but I don't think this is a bug. If you've already collected the cloths, then you should certainly be able to open the door, no matter whose Age you're in. Now if your friend is able to link to the bahro cave without touching all cloths, that might be a bug.

**Comment by Deledrius** [comment]
I agree, it makes sense that the door should be openable by anyone who has completed that Age's journey.  However, once inside, the bahro should only link an explorer who is ready to be shown the next cave.  Hopefully each caves' interior is sufficiently closed with collision to be safe for this non-linking behavior.

**Comment by Hoikas** [comment]
I think the overall sentiment is that this isn't an issue. Closing :smile:

**Comment by bertvandepoel** [comment]
I did some further testing with a friend tonight. It seems that it works just fine. If he runs into a Bahro door I opened but he didn't complete the journels for, he just doesn't link to the Bahro cave. Just wanted to mention that that's the behaviour!
