### ISSUE TITLE
Pipeline selection should be a runtime decision.

### ISSUE THREAD

**Issue by Hoikas** [H-uru/Plasma#965]
I shouldn't have to recompile to switch between OpenGL and DirectX backends.

**Comment by dpogue** [comment]
I was literally just thinking about this yesterday, along with the [plan to move the pipeline implementations to FeatureLib](https://github.com/H-uru/Plasma/discussions/790).

Right now in plPipeline there's a plPipelineCreate helper that creates the actual pipeline... but I'm 99.9% sure plClient is the only thing that creates a pipeline, so it's probably fine to move the implementation into plClient directly.

Should we determine which pipeline to use based on hsG3DDeviceRecord stuff or something else?

**Comment by Hoikas** [comment]
I actually tried to effect that pipeline split yesterday but ran into an issue where `pl3DPipeline` contained a `plDXDevice` member, so I quickly shelved that. The attempt was because I've been wanting to get serious about offloading skinning to the GPU, and it would be nice to have the DX code in its own little jail.

I was thinking that, when we have multiple pipeline types that can run, it would be nice if we could have an internal order for preferred pipelines (eg, DirectX9On12, then DirectX 9, then OpenGL). We'd initialize the best available along that preference with the option to change the preferred pipeline on the command line. The command line option would be great for faster testing, IMO. You could run two clients simultaneously with different pipelines.

**Comment by dpogue** [comment]
This is actually done as part of https://github.com/H-uru/Plasma/pull/1039 and https://github.com/H-uru/Plasma/pull/1077

**Windows:** Tries to use DirectX, falls back to OpenGL
**Linux:** Tries to use OpenGL
**macOS:** [add Metal here], falls back to OpenGL

There's a `/Renderer` option added to force a specific pipeline for testing.
