### ISSUE TITLE
Add Console command to reset all Age SDL to default values

### ISSUE THREAD

**Issue by dpogue** [H-uru/Plasma#987]
I couldn't see anything that obviously achieved this result, but it seems like a useful thing for Age developers to be able to reset an Age to its initial state.

There's probably a more convoluted way to achieve this by removing the Age instance and creating a new one, but a simple `Age.ResetSDLStates` that happened in real-time would be ideal

**Comment by Hoikas** [comment]
It should be as simple as grabbing the `AgeSDLHook` SceneObject and resetting all of the PythonSDLModifier SDL variables to unused.
